# Generated by Django 5.2.8 on 2025-11-09 15:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_change_reaction_to_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^\\+?[0-9\\-\\s]+$', 'Enter a valid phone number.')]),
        ),
    ]
