# Generated by Django 5.2.8 on 2025-11-09 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_neighborhood_zip_code_and_more'),
        ('api', '0003_alter_profile_latitude_alter_profile_longitude'),
    ]

    operations = [
    ]
