# Generated by Django 5.2.8 on 2025-11-09 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_merge_20251109_0244'),
        ('api', '0005_remove_profile_profile_photo_post_latitude_and_more'),
    ]

    operations = [
    ]
