# Generated by Django 5.2.8 on 2025-11-09 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_merge_20251109_0403'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
